"""Add Google OAuth and password reset fields

Revision ID: 270442818a45
Revises: 
Create Date: 2026-01-04 21:22:14.646762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '270442818a45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('oauth_provider', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('reset_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('reset_token_expires', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_reset_token'), 'users', ['reset_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_reset_token'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.drop_column('users', 'reset_token_expires')
    op.drop_column('users', 'reset_token')
    op.drop_column('users', 'oauth_provider')
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###

